env:
 - CABALVER=1.18 GHCVER=7.6.3
 - CABALVER=1.18 GHCVER=7.8.4
 - CABALVER=1.22 GHCVER=7.10.1
 - CABALVER=head GHCVER=head

matrix:
 allow_failures:
  - env: CABALVER=head GHCVER=head

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - cabal-install-1.18
    - cabal-install-1.22
    - ghc-7.6.3
    - ghc-7.8.4
    - ghc-7.10.1

install:
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - cabal install --only-dependencies --enable-tests --enable-benchmarks uuid-types/uuid-types.cabal uuid/uuid.cabal

script:
 - for p in uuid-types uuid; do ./travis-scripts/build.sh $p; done

sudo: false
